name: Update Plugin Registry

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual triggering from GitHub UI
  repository_dispatch:  # Allow triggering from other repos via API
    types: [plugin-release]
  push:
    branches:
      - main
    paths:
      - 'update_registry.py'

jobs:
  update-registry:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing commits
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Update plugin registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python update_registry.py --token $GITHUB_TOKEN
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet plugins.json; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add plugins.json
          git commit -m "Auto-update plugin registry with latest versions"
          git push
      
      - name: No changes
        if: steps.check_changes.outputs.changes == 'false'
        run: |
          echo "✓ Plugin registry is already up to date"

